server:
  port: 8081
  context-path: /
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mylevel
    username: root
    password: root
mybatis:
  type-aliases-package: com.xw.test.model
  mapper-locations: classpath:mapper/*.xml